skip: true
anomalies:
  - line: |
      failure: nodepool.tests.test_commands.TestNodepoolCMD.test_config_validate

  - line: |
      Content-Type: text/x-traceback;charset=utf8,language=python

  - line: |
      File "nodepool/cmd/nodepoolcmd.py", line 353, in main
  - line: |
      return NodePoolCmd.main()
  - line: |
      File "nodepool/cmd/__init__.py", line 136, in main
  - line: |
      return cls()._main(argv=argv)
  - line: |
      File "nodepool/cmd/__init__.py", line 126, in _main
  - line: |
      return self._do_run()
  - line: |
      File "nodepool/cmd/__init__.py", line 132, in _do_run
  - line: |
      return self.run()
  - line: |
      return self.args.func()
  - line: |
      File "nodepool/cmd/nodepoolcmd.py", line 314, in config_validate
  - line: |
      File "nodepool/cmd/config_validator.py", line 144, in validate
  - line: |
      return self._compiled([], data)
  - line: |
      return base_validate(path, iteritems(data), out)
  - line: |
      raise er.MultipleInvalid(errors)
  - line: |
      voluptuous.error.MultipleInvalid: required key not provided @ data['providers'][2]['cloud']
  - line: |
      File "nodepool/build1314
  - line: |
      er.py", line 855, in _uploadImage
